server {
    listen 8104;
    location / {
        proxy_pass http://127.0.0.1:8098;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        sub_filter "</body>" "<script src=\"https://chatsnip.intrane.fr/w.js\" data-agent=\"pk_ff727373ff83ad46a1b1a01b\" defer></script></body>";
        sub_filter_once on;
    }
}
