#!/usr/bin/env python3
"""Regenerate src/globe_data.src — the embedded land dot-grid + country centroids.

Inputs (fetched fresh):
  https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json
  https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv

Land dots: 2-degree grid, point-in-polygon over country rings -> flat [lat,lon,...] pairs.
Centroids: vertex mean of each country's largest ring, keyed by ISO2 (CF-IPCountry codes).
"""
import json, csv, io, os, urllib.request

def fetch(u): return urllib.request.urlopen(u).read().decode()

gj = json.loads(fetch('https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json'))
iso3to2 = {r['alpha-3']: r['alpha-2'] for r in csv.DictReader(io.StringIO(fetch(
    'https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv')))}

def rings(f):
    g = f['geometry']
    return [g['coordinates'][0]] if g['type'] == 'Polygon' else [p[0] for p in g['coordinates']]

def inside(lon, lat, ring):
    n = len(ring); j = n - 1; c = False
    for i in range(n):
        xi, yi = ring[i]; xj, yj = ring[j]
        if ((yi > lat) != (yj > lat)) and (lon < (xj - xi) * (lat - yi) / (yj - yi) + xi): c = not c
        j = i
    return c

polys, cent = [], {}
for f in gj['features']:
    a2 = iso3to2.get(f.get('id') or f['properties'].get('ISO_A3'), '')
    best = None
    for r in rings(f):
        xs = [p[0] for p in r]; ys = [p[1] for p in r]
        bb = (min(xs), min(ys), max(xs), max(ys))
        polys.append((bb, r))
        area = (bb[2] - bb[0]) * (bb[3] - bb[1])
        if best is None or area > best[0]: best = (area, sum(xs)/len(xs), sum(ys)/len(ys))
    if a2 and best: cent[a2] = (round(best[2], 1), round(best[1], 1))

pts = []
lat = -58
while lat <= 84:
    lon = -180
    while lon < 180:
        for bb, r in polys:
            if bb[0] <= lon <= bb[2] and bb[1] <= lat <= bb[3] and inside(lon, lat, r):
                pts.append((lat, lon)); break
        lon += 2
    lat += 2

flat = []
for la, lo in pts: flat += [la, lo]
pts_j = json.dumps(flat, separators=(',', ':'))
cent_j = json.dumps({k: [v[0], v[1]] for k, v in sorted(cent.items())}, separators=(',', ':'))
esc = lambda s: s.replace('\\', '\\\\').replace('"', '\\"')
src = f'''// machine-generated by tools/gen_globe_data.py — do not edit by hand.
// Land dot-grid (2-degree, [lat,lon] flat pairs) + country centroids (ISO2 -> [lat,lon]),
// derived from johan/world.geo.json (public domain) + lukes/ISO-3166 CSV.

func globe_land_points() (s) {{ s = "{esc(pts_j)}" }}

func globe_centroids() (s) {{ s = "{esc(cent_j)}" }}
'''
out = os.path.join(os.path.dirname(__file__), '..', 'src', 'globe_data.src')
open(out, 'w').write(src)
print('wrote', out, len(src), 'bytes;', len(pts), 'dots;', len(cent), 'centroids')
